on:
  push: 
    branches:
      - master
jobs:
  tag-and-release-on-new-version:
    uses: ./.github/workflows/tag-and-release-on-new-version.yml
  deploy-to-cws:
    uses: ./.github/workflows/deploy-to-cws.yml
    needs: [tag-and-release-on-new-version]

