on:
  push: 
    branches:
      - master
jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml
  check-new-version-and-release:
    name: Checks if a new version was created with the last commit, then creates a check-new-version-create-release
    needs: [ test-and-build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Check if the version has changed
        run: ./check_version_has_changed.sh
      - if: env.VERSION_HAS_CHANGED
        uses: actions/download-artifact@v4   
        with:
          name: build-artifacts
          path: dist
      - if: env.VERSION_HAS_CHANGED
        name: Tag the current version for release
        run: git tag $CURRENT_VERSION_TAG
      - if: env.VERSION_HAS_CHANGED
        name: Create zip file for release and deployment
        run: create_zip_for_upload.sh
      - if: env.VERSION_HAS_CHANGED
        uses: actions/upload-artifact@v4
        with:
          name: compressed-build-artifact
          path: build_output/output.zip
#  deploy:
#    name: Check if it is a new version and deploy to the Chrome Web Store
#    needs: [ test-and-build ]
#    steps:
#      - 
    
